name: roadanomalies_root
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.0+3
  image_picker: ^0.8.6+3
  path_provider:
  path:
  google_maps_flutter: ^2.2.0
  location: ^4.3.0
  photo_view: ^0.14.0
  dio: ^4.0.6
  http: ^0.13.5
  video_player: ^2.4.7
  chewie:
  latlong2: ^0.8.1
  intl: ^0.17.0
  lottie: ^1.4.3
  disk_space: ^0.2.1
  platform_device_id: ^1.0.1
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  video_compress: ^3.1.0
  sensors_plus: ^1.4.0
  native_device_orientation: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
